<?php

namespace app\controllers\mobile;

use app\controllers\base\BaseController;
use abei2017\wx\Application;
use app\models\User;
use app\models\UserQrcode;
use yii;

class ApiController extends BaseController
{

    public function beforeAction($action){
        $this->layout = false;
        $this->uid = @Yii::$app->session->get('uid');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionJoin($key){
        $session = Yii::$app->session;
        $session->set('bid',$key);
        return $this->redirect(Yii::$app->params['host'].'#/my/join');
    }

    public function actionWeixin(){
        $server = (new Application())->driver("mp.server");

        $server->setMessageHandler(function($message) {
            if($message['MsgType']=='text'){
                return "我们已收到您的留言，谢谢~";
            }elseif(@$message['Event']=='subscribe' || @$message['Event']=='SCAN'){
                if(@$message['EventKey']){
                    $key = str_replace('qrscene_','',$message['EventKey']);
                    if(strpos($key,'B')){//车商二维码
                        return "欢迎关注我们的公众号~\n请点击该链接进行车商注册".Yii::$app->params['host'].'mobile/api/join?key='.intval($key);
                    }
                    $model = UserQrcode::find()->where('uid='.intval($key).' AND openid="'.$message['FromUserName'].'"')->one();
                    if(!$model){
                        $model = new UserQrcode();
                        $model->uid = intval($key);
                        $model->openid = $message['FromUserName'];
                        $model->created = time();
                        $model->save();
                    }
                }
                return "欢迎关注我们的公众号~";
            }
        });

        $response = $server->serve();
        return $response;
    }

    public function actionOauth(){
        $session = Yii::$app->session;
        $oauth = (new Application())->driver('mp.oauth');
        $user = $oauth->user();
        $model = User::find()->where(['openid'=>$user['openid']])->one();
        if($model){
            $session->set('uid',$model->id);
        }else{
            $qrcode = UserQrcode::find()->where(['openid'=>$user['openid']])->one();
            $model = new User();
            $model->attributes = $user;
            $model->sex = ($user['sex']==1)?'男':'女';
            if($qrcode) $model->rid = $qrcode->uid;
            $model->save();
            $session->set('uid',$model->id);
        }
        $url = false;
        if($session->get('url')){//是从其他地方跳转的
            $url = $session->get('url');
            $session->set('url',null);
        }
        if($user['subscribe']==1){//已关注，就跳转到URL
            if($url)
                return $this->redirect($url);
            else
                return $this->redirect('/');
        }else{//未关注就跳转到个人中心
            return $this->redirect('/mobile/site/subscribe');
        }
    }

    public function actionMenu(){
        $this->layout = false;
        $json = '{
            "button": [
                {
                    "type": "view", 
                    "name": "首页", 
                    "url": "http://test.iamlk.cn/", 
                    "sub_button": [ ]
                }, 
                {
                    "type": "view", 
                    "name": "i拼车", 
                    "url": "http://test.iamlk.cn/", 
                    "sub_button": [ ]
                }, 
                {
                    "type": "view", 
                    "name": "个人中心", 
                    "url": "http://test.iamlk.cn/", 
                    "sub_button": [ ]
                }
            ]
        }';
        $menu = (new Application())->driver("mp.menu");
        $menu->create($json);
        exit;
    }
}
