<?php
/**
 * Created by PhpStorm.
 * User: Leonidax
 * Date: 2018/10/8
 * Time: 下午11:00
 */

namespace app\controllers\mobile;


use app\controllers\base\MController;
use app\models\Business;
use abei2017\wx\Application;
use app\models\User;
use app\models\UserBusiness;

class BusinessController extends MController{

    public function beforeAction($action)
    {
        $this->checkUser();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionQrcode(){
        $model = UserBusiness::find()->where('uid='.$this->uid)->one();
        if(!$model){
            return $this->json(404,'您还不是车商');
        }elseif(!$model->is_checked){
            return $this->json(404,'您申请成为车商还没有通过审核');
        }elseif(!$model->is_manager){
            return $this->json(404,'您不是车商管理员');
        }
        $qrcode = (new Application())->driver("mp.qrcode");
        $r  = $qrcode->strTemp(2592000,$model->id.'B');
        $this->data['data']['qrcode'] = 'https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket='.@$r['ticket'];
        return $this->json();
    }

    public function actionRegister(){


    }

}