<?php

namespace app\controllers\base;

use yii\web\Controller;

class AController extends Controller
{
    protected $post = [];

    protected $data = [
        'code'=>200,
        'data'=>[],
        'message'=>'操作成功'
        ];

    private $error = [
        200=>'操作成功',
        300=>'未登录',
        301=>'用户名或密码错误',
        400=>'请求方式错误：POST或GET反了',
        401=>'插入数据失败：',
        402=>'更新数据失败：',
        403=>'删除数据失败：',
    ];

    public function beforeAction($action){
        $json_str = file_get_contents('php://input');
        if(empty($json_str)) return $this->json(400);
        $this->post = json_decode($json_str,true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function json($code=200,$msg=''){
        $this->data['code'] = $code;
        $this->data['message'] = $this->error[$code].$msg;
        echo json_encode($this->data);
    }
}
