<?php

namespace app\controllers\base;


class MController extends BaseController
{
    public $uid = 1;

    public function beforeAction($action){
        $this->layout = false;
        $post = file_get_contents('php://input');
        if(empty($post)) return $this->json(400);
        $this->post = json_decode($post,true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
