<?php

namespace app\controllers\admin;

use app\controllers\base\AController;
use app\models\AdminPermission;
use app\models\AdminR2P;
use app\models\AdminRole;

class PermissionController extends AController
{

    public function beforeAction($action)
    {
        $this->layout = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionDelete(){
        if(!$_POST) return $this->json(400);
        if(empty($_POST['id'])) return $this->json(403,'权限ID不能为空');
        $model = AdminRole::find($_POST['id'])->one();
        if(empty($model)) return $this->json(403,'该权限不存在');
        $model->delete();
        return $this->json();
    }

    public function actionList($p=1)
    {
        $count = AdminPermission::find()->count();
        $list = AdminPermission::find()->offset(($p-1)*20)->limit(20)->all();
        $data = ['total'=>$count];
        $l2 = [];
        foreach($list as $li){
            $l2[] = $li->attributes;
        }
        $data['list'] = $l2;
        $this->data['data'] = $data;
        return $this->json();
    }

    public function actionAdd()
    {
        if(!$_POST) return $this->json(400);
        $model = new AdminPermission();
        $model->attributes = $_POST;
        if($model->save()) {
            return $this->json();
        }else{
            $list = $model->getFirstErrors();
            $msg = '';
            foreach($list as $key=>$value){
                $msg .= $value;
            }
            return $this->json(401,$msg);
        }
    }

    public function actionEdit(){
        if(!$_POST) return $this->json(400);
        if(empty($_POST['id'])) return $this->json(402,'权限ID不能为空');
        $model = AdminPermission::find($_POST['id'])->one();
        if(empty($model)) return $this->json(402,'该权限不存在');
        $model->attributes = $_POST;
        if($model->save()) {
            return $this->json();
        }else{
            $list = $model->getFirstErrors();
            $msg = '';
            foreach($list as $key=>$value){
                $msg .= $value;
            }
            return $this->json(402,$msg);
        }
    }

}
