<?php

namespace app\controllers\admin;


use yii\web\Controller;

class SiteController extends Controller
{

    public function beforeAction($action)
    {
        $this->layout = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
    $this->layout = false;
    return $this->render('index');
    }

    public function actionLogin(){
    $this->layout = false;
    return $this->render('login');
    }
}
